// ==========================================================================
// Project:   TableView.Movie Fixtures
// Copyright: ©2010 My Company, Inc.
// ==========================================================================
/*globals TableView */

sc_require('models/movie');

/**
  Since this is a sample app, the "fixtures" directory is renamed to 
  "fixtures-prod", meaming this fixture data will be available at all times,
  even in production mode.
*/
TableView.Movie.FIXTURES = [
  {'seen': '0', 'rating': '9.1', 'votes': '215405', 'title': 'The Shawshank Redemption'},
   {'seen': '0', 'rating': '8.8', 'votes': '206072', 'title': 'The Lord of the Rings: The Fellowship of the Ring'},

   {'seen': '0', 'rating': '8.6', 'votes': '188811', 'title': 'The Matrix'},
   {'seen': '0', 'rating': '8.8', 'votes': '185100', 'title': 'Pulp Fiction'},
   {'seen': '0', 'rating': '9.1', 'votes': '178881', 'title': 'The Godfather'},
   {'seen': '0', 'rating': '8.8', 'votes': '176346', 'title': 'Star Wars'},
   {'seen': '0', 'rating': '8.9', 'votes': '162436', 'title': 'The Lord of the Rings: The Return of the King'},
   {'seen': '0', 'rating': '8.7', 'votes': '162001', 'title': 'The Lord of the Rings: The Two Towers'},
   {'seen': '0', 'rating': '8.6', 'votes': '160135', 'title': 'Fight Club'},
   {'seen': '0', 'rating': '8.5', 'votes': '143775', 'title': 'American Beauty'},
   {'seen': '0', 'rating': '8.8', 'votes': '139813', 'title': 'Star Wars: Episode V - The Empire Strikes Back'},
   {'seen': '0', 'rating': '8.7', 'votes': '136641', 'title': 'The Usual Suspects'},
   {'seen': '0', 'rating': '8.4', 'votes': '131936', 'title': 'Saving Private Ryan'},
   {'seen': '0', 'rating': '8.8', 'votes': '130036', 'title': "Schindler's List"},
   {'seen': '0', 'rating': '8.2', 'votes': '125831', 'title': 'The Sixth Sense'},
   {'seen': '0', 'rating': '8.3', 'votes': '125224', 'title': 'Forrest Gump'},
   {'seen': '0', 'rating': '8.1', 'votes': '125137', 'title': 'Gladiator'},
   {'seen': '0', 'rating': '8.6', 'votes': '124731', 'title': 'Memento'},
   {'seen': '0', 'rating': '8.5', 'votes': '121730', 'title': 'Se7en'},
   {'seen': '0', 'rating': '8.7', 'votes': '120597', 'title': 'Raiders of the Lost Ark'},
   {'seen': '0', 'rating': '8.3', 'votes': '120485', 'title': 'Braveheart'},
   {'seen': '0', 'rating': '8.6', 'votes': '119366', 'title': 'The Silence of the Lambs'},
   {'seen': '0', 'rating': '7', 'votes': '117267', 'title': 'Titanic'},
   {'seen': '0', 'rating': '6.3', 'votes': '113240', 'title': 'Star Wars: Episode I - The Phantom Menace'},
   {'seen': '0', 'rating': '8.2', 'votes': '111044', 'title': 'Star Wars: Episode VI - Return of the Jedi'},
   {'seen': '0', 'rating': '8.2', 'votes': '102337', 'title': 'Terminator 2: Judgment Day'},
   {'seen': '0', 'rating': '9', 'votes': '101625', 'title': 'The Godfather: Part II'},
   {'seen': '0', 'rating': '8', 'votes': '100521', 'title': 'Pirates of the Caribbean: The Curse of the Black Pearl'},
   {'seen': '0', 'rating': '8.2', 'votes': '97734', 'title': 'Kill Bill: Vol. 1'},
   {'seen': '0', 'rating': '8', 'votes': '96012', 'title': 'Star Wars: Episode III - Revenge of the Sith'},
   {'seen': '0', 'rating': '8.7', 'votes': '94979', 'title': 'Goodfellas'},
   {'seen': '0', 'rating': '8.4', 'votes': '94930', 'title': 'Reservoir Dogs'},
   {'seen': '0', 'rating': '8.3', 'votes': '94455', 'title': 'Blade Runner'},
   {'seen': '0', 'rating': '8.8', 'votes': '94055', 'title': "One Flew Over the Cuckoo's Nest"},
   {'seen': '0', 'rating': '8.4', 'votes': '93766', 'title': 'Batman Begins'},
   {'seen': '0', 'rating': '8.1', 'votes': '92155', 'title': 'Back to the Future'},
   {'seen': '0', 'rating': '8.4', 'votes': '91239', 'title': 'Sin City'},
   {'seen': '0', 'rating': '6.9', 'votes': '90430', 'title': 'Star Wars: Episode II - Attack of the Clones'},
   {'seen': '0', 'rating': '8.4', 'votes': '88992', 'title': 'L.A. Confidential'},
   {'seen': '0', 'rating': '8', 'votes': '88541', 'title': 'Shrek'},
   {'seen': '0', 'rating': '8.4', 'votes': '88499', 'title': 'A Clockwork Orange'},
   {'seen': '0', 'rating': '8.8', 'votes': '87517', 'title': 'Casablanca'},
   {'seen': '0', 'rating': '8.5', 'votes': '87391', 'title': 'American History X'},
   {'seen': '0', 'rating': '8.5', 'votes': '86478', 'title': 'Apocalypse Now'},
   {'seen': '0', 'rating': '8.3', 'votes': '85723', 'title': 'Donnie Darko'},
   {'seen': '0', 'rating': '7.4', 'votes': '85323', 'title': 'Spider-Man'},
   {'seen': '0', 'rating': '8.6', 'votes': '85077', 'title': "Le Fabuleux destin d'Am"},
   {'seen': '0', 'rating': '8.5', 'votes': '85042', 'title': 'Eternal Sunshine of the Spotless Mind'},
   {'seen': '0', 'rating': '8.1', 'votes': '84206', 'title': 'The Green Mile'},
   {'seen': '0', 'rating': '8.4', 'votes': '83929', 'title': 'Alien'},
   {'seen': '0', 'rating': '8.2', 'votes': '83897', 'title': 'Fargo'},
   {'seen': '0', 'rating': '8.7', 'votes': '83862', 'title': 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb'},
   {'seen': '0', 'rating': '8.3', 'votes': '83435', 'title': '2001: A Space Odyssey'},
   {'seen': '0', 'rating': '8.3', 'votes': '83084', 'title': 'Aliens'},
   {'seen': '0', 'rating': '8', 'votes': '81813', 'title': 'Twelve Monkeys'},
   {'seen': '0', 'rating': '8.4', 'votes': '81685', 'title': 'Monty Python and the Holy Grail'},
   {'seen': '0', 'rating': '8.1', 'votes': '80477', 'title': 'Indiana Jones and the Last Crusade'},
   {'seen': '0', 'rating': '7.8', 'votes': '79527', 'title': 'The Truman Show'},
   {'seen': '0', 'rating': '7.9', 'votes': '78718', 'title': 'The Terminator'},
   {'seen': '0', 'rating': '8.6', 'votes': '78346', 'title': 'Citizen Kane'},
   {'seen': '0', 'rating': '6.1', 'votes': '77696', 'title': 'Independence Day'},
   {'seen': '0', 'rating': '8', 'votes': '77564', 'title': 'Die Hard'},
   {'seen': '0', 'rating': '8.5', 'votes': '77344', 'title': 'L'},
   {'seen': '0', 'rating': '7.5', 'votes': '76946', 'title': 'Jurassic Park'},
   {'seen': '0', 'rating': '7', 'votes': '76262', 'title': 'The Matrix Reloaded'},
   {'seen': '0', 'rating': '7.9', 'votes': '75870', 'title': 'Good Will Hunting'},
   {'seen': '0', 'rating': '8.4', 'votes': '73221', 'title': 'Requiem for a Dream'},
   {'seen': '0', 'rating': '8.2', 'votes': '71708', 'title': 'Kill Bill: Vol. 2'},
   {'seen': '0', 'rating': '8', 'votes': '71634', 'title': 'The Big Lebowski'},
   {'seen': '0', 'rating': '8.4', 'votes': '71316', 'title': 'The Shining'},
   {'seen': '0', 'rating': '7.8', 'votes': '71224', 'title': 'Being John Malkovich'},
   {'seen': '0', 'rating': '8.6', 'votes': '70599', 'title': 'Psycho'},
   {'seen': '0', 'rating': '7.2', 'votes': '70455', 'title': 'The Fifth Element'},
   {'seen': '0', 'rating': '8', 'votes': '70050', 'title': 'Trainspotting'},
   {'seen': '0', 'rating': '8.2', 'votes': '69523', 'title': 'The Princess Bride'},
   {'seen': '0', 'rating': '7.7', 'votes': '68746', 'title': 'Minority Report'},
   {'seen': '0', 'rating': '8.3', 'votes': '67182', 'title': 'Crash'},
   {'seen': '0', 'rating': '7.9', 'votes': '66600', 'title': 'Lost in Translation'},
   {'seen': '0', 'rating': '8', 'votes': '66039', 'title': 'Snatch.'},
   {'seen': '0', 'rating': '6.8', 'votes': '66029', 'title': 'Men in Black'},
   {'seen': '0', 'rating': '8.3', 'votes': '65909', 'title': 'V for Vendetta'},
   {'seen': '0', 'rating': '8.5', 'votes': '65692', 'title': 'Taxi Driver'},
   {'seen': '0', 'rating': '8.2', 'votes': '65359', 'title': 'Full Metal Jacket'},
   {'seen': '0', 'rating': '7.8', 'votes': '65085', 'title': 'King Kong'},
   {'seen': '0', 'rating': '8.2', 'votes': '65040', 'title': 'Wo hu cang long'},
   {'seen': '0', 'rating': '7.2', 'votes': '64378', 'title': "Harry Potter and the Sorcerer's Stone"},
   {'seen': '0', 'rating': '8.3', 'votes': '64263', 'title': 'Jaws'},
   {'seen': '0', 'rating': '8.2', 'votes': '63885', 'title': 'Finding Nemo'},
   {'seen': '0', 'rating': '7.8', 'votes': '63470', 'title': 'Spider-Man 2'},
   {'seen': '0', 'rating': '8', 'votes': '62772', 'title': 'Heat'},
   {'seen': '0', 'rating': '7.7', 'votes': '62299', 'title': 'Moulin Rouge!'},
   {'seen': '0', 'rating': '7.5', 'votes': '62296', 'title': "Ocean's Eleven"},
   {'seen': '0', 'rating': '6.7', 'votes': '62294', 'title': 'War of the Worlds'},
   {'seen': '0', 'rating': '8', 'votes': '62085', 'title': 'Magnolia'},
   {'seen': '0', 'rating': '7.3', 'votes': '61712', 'title': 'X-Men'},
   {'seen': '0', 'rating': '8', 'votes': '60784', 'title': 'Groundhog Day'},
   {'seen': '0', 'rating': '8', 'votes': '60516', 'title': 'Toy Story'},
   {'seen': '0', 'rating': '5.7', 'votes': '59402', 'title': 'Armageddon'},
   {'seen': '0', 'rating': '7.6', 'votes': '59263', 'title': 'Catch Me If You Can'},
   {'seen': '0', 'rating': '7.8', 'votes': '58896', 'title': 'A Beautiful Mind'},
   {'seen': '0', 'rating': '7.1', 'votes': '58581', 'title': 'Rock, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '58325', 'title': 'Fugitive, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '57968', 'title': 'Harry Potter and the Chamber of Secrets '},
   {'seen': '0', 'rating': '7.1', 'votes': '57108', 'title': "There's Something About Mary "},
   {'seen': '0', 'rating': '7.3', 'votes': '57091', 'title': 'Dogma '},
   {'seen': '0', 'rating': '8.3', 'votes': '57041', 'title': 'Incredibles, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '56864', 'title': 'Matrix Revolutions, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '56494', 'title': 'E.T. the Extra-Terrestrial '},
   {'seen': '0', 'rating': '7.7', 'votes': '56450', 'title': 'As Good as It Gets '},
   {'seen': '0', 'rating': '7.9', 'votes': '56244', 'title': 'Rain Man '},
   {'seen': '0', 'rating': '7.9', 'votes': '56206', 'title': 'Brokeback Mountain '},
   {'seen': '0', 'rating': '7.9', 'votes': '55972', 'title': 'X2 '},
   {'seen': '0', 'rating': '8.7', 'votes': '55543', 'title': 'Rear Window '},
   {'seen': '0', 'rating': '6.9', 'votes': '55327', 'title': 'Signs '},
   {'seen': '0', 'rating': '8.1', 'votes': '54173', 'title': 'Toy Story 2 '},
   {'seen': '0', 'rating': '6.8', 'votes': '54144', 'title': 'American Pie '},
   {'seen': '0', 'rating': '7.9', 'votes': '54069', 'title': 'Monsters, Inc. '},
   {'seen': '0', 'rating': '7.7', 'votes': '53768', 'title': 'Dead Poets Society '},
   {'seen': '0', 'rating': '7', 'votes': '53377', 'title': 'Scream '},
   {'seen': '0', 'rating': '7.4', 'votes': '53244', 'title': 'Sleepy Hollow '},
   {'seen': '0', 'rating': '7.9', 'votes': '53200', 'title': 'Almost Famous '},
   {'seen': '0', 'rating': '8', 'votes': '53200', 'title': 'Big Fish '},
   {'seen': '0', 'rating': '8.6', 'votes': '52946', 'title': "It's a Wonderful Life "},
   {'seen': '0', 'rating': '7', 'votes': '52248', 'title': 'Troy '},
   {'seen': '0', 'rating': '7.9', 'votes': '51949', 'title': 'Clerks. '},
   {'seen': '0', 'rating': '7.8', 'votes': '51262', 'title': 'Traffic '},
   {'seen': '0', 'rating': '8.8', 'votes': '51192', 'title': 'Cidade de Deus '},
   {'seen': '0', 'rating': '7.9', 'votes': '51026', 'title': 'Mulholland Dr. '},
   {'seen': '0', 'rating': '7.5', 'votes': '50838', 'title': 'Apollo 13 '},
   {'seen': '0', 'rating': '8.3', 'votes': '50808', 'title': 'Million Dollar Baby '},
   {'seen': '0', 'rating': '7.5', 'votes': '50744', 'title': 'Batman '},
   {'seen': '0', 'rating': '7.4', 'votes': '50626', 'title': 'Shakespeare in Love '},
   {'seen': '0', 'rating': '8.4', 'votes': '50610', 'title': 'Vita '},
   {'seen': '0', 'rating': '8.2', 'votes': '50545', 'title': 'Wizard of Oz, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '50179', 'title': 'Gangs of New York '},
   {'seen': '0', 'rating': '6', 'votes': '49788', 'title': 'Blair Witch Project, The '},
   {'seen': '0', 'rating': '7', 'votes': '49578', 'title': 'Eyes Wide Shut '},
   {'seen': '0', 'rating': '8', 'votes': '49438', 'title': 'Scarface '},
   {'seen': '0', 'rating': '8', 'votes': '49330', 'title': 'Lock, Stock and Two Smoking Barrels '},
   {'seen': '0', 'rating': '8.1', 'votes': '49131', 'title': 'Serenity '},
   {'seen': '0', 'rating': '7.4', 'votes': '49082', 'title': 'Chicago '},
   {'seen': '0', 'rating': '8.5', 'votes': '48963', 'title': 'Pianist, The '},
   {'seen': '0', 'rating': '8.9', 'votes': '48897', 'title': 'Buono, il brutto, il cattivo, Il '},
   {'seen': '0', 'rating': '7.8', 'votes': '48877', 'title': 'O Brother, Where Art Thou? '},
   {'seen': '0', 'rating': '8.3', 'votes': '48839', 'title': 'Bowling for Columbine '},
   {'seen': '0', 'rating': '8.3', 'votes': '48445', 'title': 'Amadeus '},
   {'seen': '0', 'rating': '8.1', 'votes': '48391', 'title': 'Platoon '},
   {'seen': '0', 'rating': '7.3', 'votes': '48372', 'title': "Pirates of the Caribbean: Dead Man's Chest "},
   {'seen': '0', 'rating': '7.1', 'votes': '48280', 'title': 'Face/Off '},
   {'seen': '0', 'rating': '8', 'votes': '48124', 'title': 'Garden State '},
   {'seen': '0', 'rating': '7.8', 'votes': '47942', 'title': 'Others, The '},
   {'seen': '0', 'rating': '6.8', 'votes': '47902', 'title': 'Artificial Intelligence: AI '},
   {'seen': '0', 'rating': '7.1', 'votes': '47718', 'title': 'Unbreakable '},
   {'seen': '0', 'rating': '5.7', 'votes': '47620', 'title': 'Mission: Impossible II '},
   {'seen': '0', 'rating': '6.5', 'votes': '47468', 'title': 'Austin Powers: The Spy Who Shagged Me '},
   {'seen': '0', 'rating': '7.3', 'votes': '47351', 'title': 'Passion of the Christ, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '47333', 'title': 'Mummy, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '47216', 'title': 'Last Samurai, The '},
   {'seen': '0', 'rating': '8.8', 'votes': '47059', 'title': 'Shichinin no samurai '},
   {'seen': '0', 'rating': '8.6', 'votes': '47054', 'title': 'North by Northwest '},
   {'seen': '0', 'rating': '7.2', 'votes': '47002', 'title': 'Indiana Jones and the Temple of Doom '},
   {'seen': '0', 'rating': '8', 'votes': '46766', 'title': 'Exorcist, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '46702', 'title': 'Cast Away '},
   {'seen': '0', 'rating': '7.8', 'votes': '46487', 'title': 'Harry Potter and the Goblet of Fire '},
   {'seen': '0', 'rating': '7.9', 'votes': '46182', 'title': 'Lion King, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '46068', 'title': 'Fahrenheit 9/11 '},
   {'seen': '0', 'rating': '8', 'votes': '45784', 'title': 'Mystic River '},
   {'seen': '0', 'rating': '5.3', 'votes': '45530', 'title': 'Pearl Harbor '},
   {'seen': '0', 'rating': '7.6', 'votes': '45359', 'title': 'Black Hawk Down '},
   {'seen': '0', 'rating': '8.5', 'votes': '45061', 'title': 'Vertigo '},
   {'seen': '0', 'rating': '6.8', 'votes': '45017', 'title': 'Terminator 3: Rise of the Machines '},
   {'seen': '0', 'rating': '8.1', 'votes': '44992', 'title': 'Life of Brian '},
   {'seen': '0', 'rating': '7.3', 'votes': '44512', 'title': 'Contact '},
   {'seen': '0', 'rating': '6.6', 'votes': '44474', 'title': 'Mission: Impossible '},
   {'seen': '0', 'rating': '7.6', 'votes': '44261', 'title': 'South Park: Bigger Longer & Uncut '},
   {'seen': '0', 'rating': '6.8', 'votes': '43897', 'title': 'Vanilla Sky '},
   {'seen': '0', 'rating': '7.2', 'votes': '43845', 'title': 'Jerry Maguire '},
   {'seen': '0', 'rating': '8.1', 'votes': '43476', 'title': 'Lola rennt '},
   {'seen': '0', 'rating': '7.4', 'votes': '43391', 'title': 'Bourne Identity, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '43102', 'title': 'Saw '},
   {'seen': '0', 'rating': '7.7', 'votes': '43077', 'title': 'Collateral '},
   {'seen': '0', 'rating': '7.7', 'votes': '43032', 'title': 'Shrek 2 '},
   {'seen': '0', 'rating': '7.5', 'votes': '42906', 'title': 'Royal Tenenbaums, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '42837', 'title': 'Harry Potter and the Prisoner of Azkaban '},
   {'seen': '0', 'rating': '7.3', 'votes': '42664', 'title': 'Ring, The '},
   {'seen': '0', 'rating': '7.9', 'votes': '42663', 'title': 'Untouchables, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '42427', 'title': 'Austin Powers: International Man of Mystery '},
   {'seen': '0', 'rating': '6.5', 'votes': '42301', 'title': 'Top Gun '},
   {'seen': '0', 'rating': '7.5', 'votes': '42095', 'title': 'Charlie and the Chocolate Factory '},
   {'seen': '0', 'rating': '8.2', 'votes': '41801', 'title': 'Unforgiven '},
   {'seen': '0', 'rating': '7.3', 'votes': '41783', 'title': 'Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '41740', 'title': 'Village, The '},
   {'seen': '0', 'rating': '7', 'votes': '41689', 'title': 'Meet the Parents '},
   {'seen': '0', 'rating': '8.1', 'votes': '41669', 'title': 'Stand by Me '},
   {'seen': '0', 'rating': '7.8', 'votes': '41636', 'title': "Ferris Bueller's Day Off "},
   {'seen': '0', 'rating': '8.7', 'votes': '41605', 'title': '12 Angry Men '},
   {'seen': '0', 'rating': '7.1', 'votes': '41564', 'title': 'Speed '},
   {'seen': '0', 'rating': '7', 'votes': '41526', 'title': 'X-Men: The Last Stand '},
   {'seen': '0', 'rating': '7.7', 'votes': '41498', 'title': 'Road to Perdition '},
   {'seen': '0', 'rating': '7.8', 'votes': '41421', 'title': 'Edward Scissorhands '},
   {'seen': '0', 'rating': '6.7', 'votes': '41395', 'title': 'Starship Troopers '},
   {'seen': '0', 'rating': '8.5', 'votes': '41145', 'title': 'To Kill a Mockingbird '},
   {'seen': '0', 'rating': '6.5', 'votes': '41113', 'title': 'Da Vinci Code, The '},
   {'seen': '0', 'rating': '8.6', 'votes': '41049', 'title': 'Lawrence of Arabia '},
   {'seen': '0', 'rating': '7.7', 'votes': '40989', 'title': 'Butterfly Effect, The '},
   {'seen': '0', 'rating': '8', 'votes': '40684', 'title': 'Brazil '},
   {'seen': '0', 'rating': '8.5', 'votes': '40191', 'title': 'Sen to Chihiro no kamikakushi '},
   {'seen': '0', 'rating': '7.1', 'votes': '39903', 'title': 'Superman Returns '},
   {'seen': '0', 'rating': '7.5', 'votes': '39729', 'title': 'Jackie Brown '},
   {'seen': '0', 'rating': '7.5', 'votes': '39636', 'title': 'Chasing Amy '},
   {'seen': '0', 'rating': '7.6', 'votes': '39614', 'title': 'Ghost Busters '},
   {'seen': '0', 'rating': '7.3', 'votes': '39510', 'title': 'Three Kings '},
   {'seen': '0', 'rating': '7.9', 'votes': '39474', 'title': 'Casino '},
   {'seen': '0', 'rating': '7.1', 'votes': '39364', 'title': 'True Lies '},
   {'seen': '0', 'rating': '7.1', 'votes': '39165', 'title': 'Back to the Future Part II '},
   {'seen': '0', 'rating': '6.7', 'votes': '39017', 'title': 'Dumb & Dumber '},
   {'seen': '0', 'rating': '8.1', 'votes': '38930', 'title': 'Deer Hunter, The '},
   {'seen': '0', 'rating': '3.5', 'votes': '38898', 'title': 'Batman & Robin '},
   {'seen': '0', 'rating': '8', 'votes': '38766', 'title': 'Gone with the Wind '},
   {'seen': '0', 'rating': '7.7', 'votes': '38751', 'title': 'Office Space '},
   {'seen': '0', 'rating': '7.6', 'votes': '38498', 'title': 'High Fidelity '},
   {'seen': '0', 'rating': '6.7', 'votes': '38468', 'title': 'Patriot, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '38304', 'title': 'Ying xiong '},
   {'seen': '0', 'rating': '7.9', 'votes': '38228', 'title': 'Insider, The '},
   {'seen': '0', 'rating': '6.2', 'votes': '38005', 'title': 'Day After Tomorrow, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '37993', 'title': 'Finding Neverland '},
   {'seen': '0', 'rating': '8.5', 'votes': '37943', 'title': 'Boot, Das '},
   {'seen': '0', 'rating': '8.1', 'votes': '37916', 'title': 'Graduate, The '},
   {'seen': '0', 'rating': '8.4', 'votes': '37841', 'title': 'Raging Bull '},
   {'seen': '0', 'rating': '6.8', 'votes': '37627', 'title': 'From Dusk Till Dawn '},
   {'seen': '0', 'rating': '6.3', 'votes': '37521', 'title': 'Hannibal '},
   {'seen': '0', 'rating': '7.8', 'votes': '37477', 'title': 'Dances with Wolves '},
   {'seen': '0', 'rating': '5.6', 'votes': '37278', 'title': 'Lost World: Jurassic Park, The '},
   {'seen': '0', 'rating': '5.5', 'votes': '37171', 'title': 'Planet of the Apes '},
   {'seen': '0', 'rating': '7', 'votes': '37056', 'title': 'Napoleon Dynamite '},
   {'seen': '0', 'rating': '6.5', 'votes': '37043', 'title': 'Mr. & Mrs. Smith '},
   {'seen': '0', 'rating': '7.2', 'votes': '36504', 'title': 'Interview with the Vampire: The Vampire Chronicles '},
   {'seen': '0', 'rating': '6.4', 'votes': '36479', 'title': 'Bruce Almighty '},
   {'seen': '0', 'rating': '7.8', 'votes': '36464', 'title': 'Blues Brothers, The '},
   {'seen': '0', 'rating': '7.6', 'votes': '36408', 'title': 'Game, The '},
   {'seen': '0', 'rating': '7.1', 'votes': '36211', 'title': "Devil's Advocate, The "},
   {'seen': '0', 'rating': '6.1', 'votes': '36137', 'title': 'Mars Attacks! '},
   {'seen': '0', 'rating': '7.9', 'votes': '36096', 'title': 'Sideways '},
   {'seen': '0', 'rating': '6.9', 'votes': '36054', 'title': 'Notting Hill '},
   {'seen': '0', 'rating': '7.6', 'votes': '35973', 'title': 'Boogie Nights '},
   {'seen': '0', 'rating': '7', 'votes': '35789', 'title': 'I, Robot '},
   {'seen': '0', 'rating': '7.3', 'votes': '35735', 'title': '28 Days Later... '},
   {'seen': '0', 'rating': '6.4', 'votes': '35724', 'title': 'Con Air '},
   {'seen': '0', 'rating': '7.8', 'votes': '35703', 'title': 'Love Actually '},
   {'seen': '0', 'rating': '7.9', 'votes': '35635', 'title': 'Shaun of the Dead '},
   {'seen': '0', 'rating': '7.8', 'votes': '35576', 'title': '21 Grams '},
   {'seen': '0', 'rating': '7.8', 'votes': '35527', 'title': 'True Romance '},
   {'seen': '0', 'rating': '7.6', 'votes': '35459', 'title': 'Gattaca '},
   {'seen': '0', 'rating': '7.5', 'votes': '35400', 'title': 'Predator '},
   {'seen': '0', 'rating': '5.9', 'votes': '35335', 'title': 'Twister '},
   {'seen': '0', 'rating': '8.5', 'votes': '35311', 'title': 'Chinatown '},
   {'seen': '0', 'rating': '6.5', 'votes': '34915', 'title': 'Cruel Intentions '},
   {'seen': '0', 'rating': '7.3', 'votes': '34860', 'title': 'Wedding Crashers '},
   {'seen': '0', 'rating': '7.8', 'votes': '34552', 'title': 'Adaptation. '},
   {'seen': '0', 'rating': '7.3', 'votes': '34449', 'title': 'Ice Age '},
   {'seen': '0', 'rating': '7.3', 'votes': '34335', 'title': 'Total Recall '},
   {'seen': '0', 'rating': '6.8', 'votes': '34259', 'title': 'Natural Born Killers '},
   {'seen': '0', 'rating': '7.1', 'votes': '34257', 'title': 'Die Hard: With a Vengeance '},
   {'seen': '0', 'rating': '6.8', 'votes': '34234', 'title': 'Back to the Future Part III '},
   {'seen': '0', 'rating': '5.7', 'votes': '34156', 'title': 'Gone in Sixty Seconds '},
   {'seen': '0', 'rating': '7.4', 'votes': '34012', 'title': 'Godfather: Part III, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '33893', 'title': 'Breakfast Club, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '33789', 'title': 'Batman Returns '},
   {'seen': '0', 'rating': '7.9', 'votes': '33769', 'title': 'JFK '},
   {'seen': '0', 'rating': '8.3', 'votes': '33754', 'title': 'Some Like It Hot '},
   {'seen': '0', 'rating': '6.9', 'votes': '33700', 'title': 'American Psycho '},
   {'seen': '0', 'rating': '5.4', 'votes': '33681', 'title': 'Batman Forever '},
   {'seen': '0', 'rating': '7.1', 'votes': '33630', 'title': 'Talented Mr. Ripley, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '33551', 'title': 'Thin Red Line, The '},
   {'seen': '0', 'rating': '8.1', 'votes': '33456', 'title': 'Walk the Line '},
   {'seen': '0', 'rating': '7.6', 'votes': '33404', 'title': 'Aviator, The '},
   {'seen': '0', 'rating': '7.3', 'votes': '33272', 'title': 'Fear and Loathing in Las Vegas '},
   {'seen': '0', 'rating': '6.2', 'votes': '33271', 'title': 'Air Force One '},
   {'seen': '0', 'rating': '7.4', 'votes': '33212', 'title': 'Bourne Supremacy, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '33171', 'title': 'Close Encounters of the Third Kind '},
   {'seen': '0', 'rating': '7.8', 'votes': '33114', 'title': 'Beauty and the Beast '},
   {'seen': '0', 'rating': '7.5', 'votes': '32926', 'title': 'Hunt for Red October, The '},
   {'seen': '0', 'rating': '5.6', 'votes': '32877', 'title': "Charlie's Angels "},
   {'seen': '0', 'rating': '7.5', 'votes': '32817', 'title': 'Few Good Men, A '},
   {'seen': '0', 'rating': '6.8', 'votes': '32708', 'title': 'Blade '},
   {'seen': '0', 'rating': '6.8', 'votes': '32536', 'title': 'Jay and Silent Bob Strike Back '},
   {'seen': '0', 'rating': '6.9', 'votes': '32447', 'title': 'Panic Room '},
   {'seen': '0', 'rating': '7.8', 'votes': '32415', 'title': 'Rocky '},
   {'seen': '0', 'rating': '8', 'votes': '32386', 'title': 'Ed Wood '},
   {'seen': '0', 'rating': '7.7', 'votes': '32381', 'title': 'Boondock Saints, The '},
   {'seen': '0', 'rating': '6.9', 'votes': '32360', 'title': "Bridget Jones's Diary "},
   {'seen': '0', 'rating': '6', 'votes': '32307', 'title': 'Alien: Resurrection '},
   {'seen': '0', 'rating': '6.2', 'votes': '32269', 'title': 'Austin Powers in Goldmember '},
   {'seen': '0', 'rating': '7.3', 'votes': '32091', 'title': 'About Schmidt '},
   {'seen': '0', 'rating': '7.3', 'votes': '32088', 'title': 'Training Day '},
   {'seen': '0', 'rating': '7.7', 'votes': '31707', 'title': 'Equilibrium '},
   {'seen': '0', 'rating': '8.3', 'votes': '31698', 'title': 'Sting, The '},
   {'seen': '0', 'rating': '6.6', 'votes': '31562', 'title': 'Pretty Woman '},
   {'seen': '0', 'rating': '6', 'votes': '31436', 'title': 'Mummy Returns, The '},
   {'seen': '0', 'rating': '5.7', 'votes': '31431', 'title': 'Scary Movie '},
   {'seen': '0', 'rating': '6.2', 'votes': '31148', 'title': 'American Pie 2 '},
   {'seen': '0', 'rating': '7.1', 'votes': '31139', 'title': 'English Patient, The '},
   {'seen': '0', 'rating': '7.8', 'votes': '31110', 'title': 'Airplane! '},
   {'seen': '0', 'rating': '6.5', 'votes': '31088', 'title': 'Analyze This '},
   {'seen': '0', 'rating': '7.6', 'votes': '31088', 'title': 'Dark City '},
   {'seen': '0', 'rating': '6.1', 'votes': '31014', 'title': 'Perfect Storm, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '30965', 'title': 'World Is Not Enough, The '},
   {'seen': '0', 'rating': '6.7', 'votes': '30915', 'title': 'Die Hard 2 '},
   {'seen': '0', 'rating': '6.5', 'votes': '30911', 'title': 'Liar Liar '},
   {'seen': '0', 'rating': '7', 'votes': '30852', 'title': 'Kingdom of Heaven '},
   {'seen': '0', 'rating': '7.6', 'votes': '30850', 'title': 'Aladdin '},
   {'seen': '0', 'rating': '7.4', 'votes': '30757', 'title': 'Chicken Run '},
   {'seen': '0', 'rating': '6.9', 'votes': '30623', 'title': 'Island, The '},
   {'seen': '0', 'rating': '7.7', 'votes': '30595', 'title': 'Fish Called Wanda, A '},
   {'seen': '0', 'rating': '7.2', 'votes': '30588', 'title': 'Erin Brockovich '},
   {'seen': '0', 'rating': '7.3', 'votes': '30519', 'title': 'Phone Booth '},
   {'seen': '0', 'rating': '7.5', 'votes': '30482', 'title': 'Master and Commander: The Far Side of the World '},
   {'seen': '0', 'rating': '6.5', 'votes': '30442', 'title': 'Home Alone '},
   {'seen': '0', 'rating': '6.9', 'votes': '30406', 'title': 'GoldenEye '},
   {'seen': '0', 'rating': '6.2', 'votes': '30400', 'title': 'Die Another Day '},
   {'seen': '0', 'rating': '7', 'votes': '30383', 'title': 'Enemy of the State '},
   {'seen': '0', 'rating': '7.6', 'votes': '30358', 'title': 'History of Violence, A '},
   {'seen': '0', 'rating': '7.9', 'votes': '30337', 'title': 'Nightmare Before Christmas, The '},
   {'seen': '0', 'rating': '7.2', 'votes': '30327', 'title': 'Insomnia '},
   {'seen': '0', 'rating': '6.5', 'votes': '30239', 'title': 'Constantine '},
   {'seen': '0', 'rating': '7.4', 'votes': '30204', 'title': 'Closer '},
   {'seen': '0', 'rating': '7.6', 'votes': '30135', 'title': 'When Harry Met Sally... '},
   {'seen': '0', 'rating': '6', 'votes': '30036', 'title': "Ocean's Twelve "},
   {'seen': '0', 'rating': '5.5', 'votes': '29926', 'title': 'Men in Black II '},
   {'seen': '0', 'rating': '6.4', 'votes': '29875', 'title': 'Mask, The '},
   {'seen': '0', 'rating': '5.9', 'votes': '29768', 'title': 'Hulk '},
   {'seen': '0', 'rating': '8', 'votes': '29715', 'title': 'Young Frankenstein '},
   {'seen': '0', 'rating': '5.3', 'votes': '29705', 'title': 'Van Helsing '},
   {'seen': '0', 'rating': '7.1', 'votes': '29649', 'title': 'Mallrats '},
   {'seen': '0', 'rating': '8.5', 'votes': '29591', 'title': 'Hotel Rwanda '},
   {'seen': '0', 'rating': '6.8', 'votes': '29570', 'title': 'Grease '},
   {'seen': '0', 'rating': '5.7', 'votes': '29551', 'title': 'Fast and the Furious, The '},
   {'seen': '0', 'rating': '8.2', 'votes': '29533', 'title': 'Annie Hall '},
   {'seen': '0', 'rating': '6.8', 'votes': '29532', 'title': 'Romeo + Juliet '},
   {'seen': '0', 'rating': '8.4', 'votes': '29508', 'title': 'Bridge on the River Kwai, The '},
   {'seen': '0', 'rating': '6.3', 'votes': '29506', 'title': 'Alien'},
   {'seen': '0', 'rating': '7.8', 'votes': '29499', 'title': 'Munich '},
   {'seen': '0', 'rating': '7.3', 'votes': '29431', 'title': 'Red Dragon '},
   {'seen': '0', 'rating': '7.4', 'votes': '29342', 'title': 'Star Trek: First Contact '},
   {'seen': '0', 'rating': '5.6', 'votes': '29296', 'title': 'Daredevil '},
   {'seen': '0', 'rating': '4.4', 'votes': '29292', 'title': 'Godzilla '},
   {'seen': '0', 'rating': '7.7', 'votes': '29260', 'title': 'Rushmore '},
   {'seen': '0', 'rating': '7.1', 'votes': '29224', 'title': 'Terminal, The '}

];

// missing a guid property - map one in
(function() {
  var guid = 1;
  TableView.Movie.FIXTURES.forEach(function(rec) {
    rec.guid = guid++;
  }, this);
})();
